packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  msw: true

minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - '@mp-lb/tools-fumadocs-preset@0.2.0'
  - '@mp-lb/tools-fumadocs-preset@0.3.0'
